version: '3.8'

networks:
  my-network:  # Customize the network name if desired
services:
  nginx:
    container_name: elearning_web
    restart: on-failure
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - uploads_volume:/app/uploads
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - my-network

  api:
    container_name: elearning_api
    build: .
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
    command: >
      sh -c "
      while ! nc -z db 5432; do
        echo 'Waiting for the database...';
        sleep 2;
      done;
      echo 'Database is ready!';
      python manage.py migrate --no-input &&
      gunicorn innovatics_elearning.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - uploads_volume:/app/uploads
    depends_on:
      - db
    networks:
      - my-network

  db:
    container_name: elearning_db
    image: postgres:16.2-alpine
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - my-network

volumes:
  uploads_volume:
  postgres_data:
