# Generated by Django 5.0 on 2023-12-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
