# Generated by Django 5.0 on 2024-01-19 09:05

import elearning.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_user', '0003_alter_user_created_alter_user_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=elearning.user.models.user_directory_path),
        ),
    ]
