# Generated by Django 5.0 on 2023-12-21 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
