# Generated by Django 5.0 on 2023-12-21 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_post', '0002_alter_post_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='elearning_post',
        ),
    ]
